import type { Startup } from "./data";

export const OFFICIAL_STARTUPS = [
  {
    id: "OPP-MGV-0001",
    company: "Secfix",
    oneLiner:
      "Verified public opportunity in Security Compliance Automation. $12M Series A led by ALSTIN Capital (announced 2026-02-25)",
    founders: [
      {
        id: "FND-MGV-0001",
        name: "Fabiola Munguia",
        role: "CEO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "FM",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-0002",
        name: "Grigory Emelianov",
        role: "co-founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "GE",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Security Compliance Automation",
    geography: "Berlin/Munich, DE",
    round: "Series A",
    ask: "$12M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Low",
    submitted: "2026-02-25",
    thesisFit: null,
    realEvent: "$12M Series A led by ALSTIN Capital (announced 2026-02-25)",
    interviewUrl: "https://www.youtube.com/watch?v=k_Rkq40O3kU",
    website: null,
    logoUrl: "/opportunity-db/assets/OPP-MGV-0001-secfix/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-0001-secfix.md",
    companyStatus: null,
    vehicle: null,
    portfolioYear: null,
  },
  {
    id: "OPP-MGV-0002",
    company: "deskbird",
    oneLiner:
      "Verified public opportunity in Hybrid Workplace Management. $13M Series A led by ALSTIN Capital, AXA Venture Partners (announced 2023-09-06)",
    founders: [
      {
        id: "FND-MGV-0003",
        name: "Ivan Cossu",
        role: "CEO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "IC",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-0004",
        name: "Jonas Hess",
        role: "co-founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "JH",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Hybrid Workplace Management",
    geography: "St. Gallen, CH",
    round: "Series A",
    ask: "$13M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Low",
    submitted: "2023-09-06",
    thesisFit: null,
    realEvent: "$13M Series A led by ALSTIN Capital, AXA Venture Partners (announced 2023-09-06)",
    interviewUrl: "https://www.youtube.com/watch?v=Flx_ZmOau68",
    website: null,
    logoUrl: "/opportunity-db/assets/OPP-MGV-0002-deskbird/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-0002-deskbird.md",
    companyStatus: null,
    vehicle: null,
    portfolioYear: null,
  },
  {
    id: "OPP-MGV-0003",
    company: "VoiceLine",
    oneLiner:
      "Verified public opportunity in Voice AI For Enterprise Frontline. EUR 10M Series A led by ALSTIN Capital, Peak (announced 2026-02-24)",
    founders: [
      {
        id: "FND-MGV-0005",
        name: "Dr. Nicolas Höflinger",
        role: "CEO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "DN",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-0010",
        name: "Sebastian Pinkas",
        role: "CTO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "SP",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Voice AI For Enterprise Frontline",
    geography: "Munich, DE",
    round: "Series A",
    ask: "EUR 10M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Low",
    submitted: "2026-02-24",
    thesisFit: null,
    realEvent: "EUR 10M Series A led by ALSTIN Capital, Peak (announced 2026-02-24)",
    interviewUrl: null,
    website: null,
    logoUrl: "/opportunity-db/assets/OPP-MGV-0003-voiceline/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-0003-voiceline.md",
    companyStatus: null,
    vehicle: null,
    portfolioYear: null,
  },
  {
    id: "OPP-MGV-0004",
    company: "Timefold",
    oneLiner:
      "Verified public opportunity in Scheduling Optimization. $13M Series A led by Alstin Capital (announced 2026-06-23)",
    founders: [
      {
        id: "FND-MGV-0006",
        name: "Maarten Vandenbroucke",
        role: "CEO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "MV",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-0009",
        name: "Geoffrey De Smet",
        role: "co-founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "GD",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Scheduling Optimization",
    geography: "Ghent, BE",
    round: "Series A",
    ask: "$13M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Low",
    submitted: "2026-06-23",
    thesisFit: null,
    realEvent: "$13M Series A led by Alstin Capital (announced 2026-06-23)",
    interviewUrl: null,
    website: null,
    logoUrl: "/opportunity-db/assets/OPP-MGV-0004-timefold/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-0004-timefold.md",
    companyStatus: null,
    vehicle: null,
    portfolioYear: null,
  },
  {
    id: "OPP-MGV-0005",
    company: "Climatiq",
    oneLiner:
      "Verified public opportunity in Carbon Intelligence API. EUR 10M Series A led by ALSTIN Capital (announced 2025-06-25)",
    founders: [
      {
        id: "FND-MGV-0007",
        name: "Hessam Lavi",
        role: "CEO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "HL",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-0011",
        name: "Philipp von Bieberstein",
        role: "CRO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "PV",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-0012",
        name: "Isis T. Baulig",
        role: "CTO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "IT",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Carbon Intelligence API",
    geography: "Berlin, DE",
    round: "Series A",
    ask: "EUR 10M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Low",
    submitted: "2025-06-25",
    thesisFit: null,
    realEvent: "EUR 10M Series A led by ALSTIN Capital (announced 2025-06-25)",
    interviewUrl: null,
    website: null,
    logoUrl: "/opportunity-db/assets/OPP-MGV-0005-climatiq/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-0005-climatiq.md",
    companyStatus: null,
    vehicle: null,
    portfolioYear: null,
  },
  {
    id: "OPP-MGV-0006",
    company: "Pliant",
    oneLiner:
      "Verified public opportunity in Corporate Cards / Spend Management. $28M Series A led by SBI Investment (announced 2023-02-17)",
    founders: [
      {
        id: "FND-MGV-0008",
        name: "Malte Rau",
        role: "CEO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "MR",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-0013",
        name: "Fabian Terner",
        role: "CPO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "FT",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Corporate Cards / Spend Management",
    geography: "Berlin, DE",
    round: "Series A",
    ask: "$28M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Low",
    submitted: "2023-02-17",
    thesisFit: null,
    realEvent: "$28M Series A led by SBI Investment (announced 2023-02-17)",
    interviewUrl: null,
    website: null,
    logoUrl: "/opportunity-db/assets/OPP-MGV-0006-pliant/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-0006-pliant.md",
    companyStatus: null,
    vehicle: null,
    portfolioYear: null,
  },
  {
    id: "OPP-MGV-US-0101",
    company: "Observe.AI",
    oneLiner:
      "Active portfolio company in Sales And Marketing. $125M Series C; $213M total disclosed funding as of 2022-04-12",
    founders: [
      {
        id: "FND-MGV-US-0101",
        name: "Swapnil Jain",
        role: "CEO & Co-Founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "SJ",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0102",
        name: "Jithendra Vepa",
        role: "CTO & Co-Founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "JV",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0103",
        name: "Akash Singh",
        role: "co-founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "AS",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0104",
        name: "Sharath Keshava Narayana",
        role: "co-founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "SK",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Sales And Marketing",
    geography: "US",
    round: "Series C",
    ask: "$125M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Medium",
    submitted: "2022-04-12",
    thesisFit: null,
    realEvent: "$125M Series C; $213M total disclosed funding as of 2022-04-12",
    interviewUrl: null,
    website: "https://observe.ai/",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0101-observe-ai/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0101-observe-ai.md",
    companyStatus: "active",
    vehicle: "MGV.VC",
    portfolioYear: 2018,
  },
  {
    id: "OPP-MGV-US-0102",
    company: "Modern Health",
    oneLiner:
      "Active portfolio company in Healthcare. $74M Series D; $172M total investment and $1.17B valuation reported in 2021",
    founders: [
      {
        id: "FND-MGV-US-0105",
        name: "Alyson Watson",
        role: "Founder and Executive Chair",
        assessed: false,
        avatar: {
          type: "initials",
          value: "AW",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0106",
        name: "Erica Johnson",
        role: "co-founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "EJ",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Healthcare",
    geography: "US",
    round: "Series D",
    ask: "$74M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Medium",
    submitted: "2021-02-11",
    thesisFit: null,
    realEvent: "$74M Series D; $172M total investment and $1.17B valuation reported in 2021",
    interviewUrl: null,
    website: "https://www.modernhealth.com/",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0102-modern-health/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0102-modern-health.md",
    companyStatus: "active",
    vehicle: "MGV.VC",
    portfolioYear: 2018,
  },
  {
    id: "OPP-MGV-US-0103",
    company: "Origin",
    oneLiner:
      "Active portfolio company in Finance And Insurance. $56M Series B at a $400M valuation; secondary database reports $68M total funding",
    founders: [
      {
        id: "FND-MGV-US-0107",
        name: "Matt Watson",
        role: "Founder & CEO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "MW",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Finance And Insurance",
    geography: "US",
    round: "Series B",
    ask: "$56M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Medium",
    submitted: "2021-08-30",
    thesisFit: null,
    realEvent: "$56M Series B at a $400M valuation; secondary database reports $68M total funding",
    interviewUrl: null,
    website: "https://useorigin.com/",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0103-origin/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0103-origin.md",
    companyStatus: "active",
    vehicle: "MGV.VC",
    portfolioYear: 2019,
  },
  {
    id: "OPP-MGV-US-0104",
    company: "Prodigal",
    oneLiner:
      "Active portfolio company in Finance And Insurance. $12M Series A announced 2021-07-22; MGV participated",
    founders: [
      {
        id: "FND-MGV-US-0108",
        name: "Shantanu Gangal",
        role: "CEO & Co-Founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "SG",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0109",
        name: "Sangram Raje",
        role: "CTO & Co-Founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "SR",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Finance And Insurance",
    geography: "US",
    round: "Series A",
    ask: "$12M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Medium",
    submitted: "2021-07-22",
    thesisFit: null,
    realEvent: "$12M Series A announced 2021-07-22; MGV participated",
    interviewUrl: null,
    website: "https://www.prodigaltech.com/",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0104-prodigal/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0104-prodigal.md",
    companyStatus: "active",
    vehicle: "MGV.VC",
    portfolioYear: 2018,
  },
  {
    id: "OPP-MGV-US-0105",
    company: "Ascend",
    oneLiner:
      "Active portfolio company in Finance And Insurance. $30M Series A; $39M total equity plus a separate $250M lending commitment",
    founders: [
      {
        id: "FND-MGV-US-0110",
        name: "Andrew Wynn",
        role: "Co-Founder & Co-CEO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "AW",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0111",
        name: "Praveen Chekuri",
        role: "Co-Founder & Co-CEO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "PC",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Finance And Insurance",
    geography: "US",
    round: "Series A",
    ask: "$30M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Medium",
    submitted: "2022-01-27",
    thesisFit: null,
    realEvent: "$30M Series A; $39M total equity plus a separate $250M lending commitment",
    interviewUrl: null,
    website: "https://www.useascend.com/",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0105-ascend/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0105-ascend.md",
    companyStatus: "active",
    vehicle: "MGV.VC",
    portfolioYear: 2021,
  },
  {
    id: "OPP-MGV-US-0106",
    company: "Authentic Insurance",
    oneLiner:
      "Active portfolio company in Finance And Insurance. $11M Series A in 2024; $16.5M total reported by a secondary database",
    founders: [
      {
        id: "FND-MGV-US-0112",
        name: "Cole Riccardi",
        role: "CEO & Cofounder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "CR",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0113",
        name: "Kyle Babirad",
        role: "COO & Cofounder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "KB",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Finance And Insurance",
    geography: "US",
    round: "Series A",
    ask: "$11M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Medium",
    submitted: "2024-03-26",
    thesisFit: null,
    realEvent: "$11M Series A in 2024; $16.5M total reported by a secondary database",
    interviewUrl: null,
    website: "https://www.authenticinsurance.com/",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0106-authentic-insurance/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0106-authentic-insurance.md",
    companyStatus: "active",
    vehicle: "MGV.VC",
    portfolioYear: 2022,
  },
  {
    id: "OPP-MGV-US-0107",
    company: "Attention",
    oneLiner: "Active portfolio company in Sales And Marketing. $30M Series B announced 2026-06-23",
    founders: [
      {
        id: "FND-MGV-US-0114",
        name: "Anis Bennaceur",
        role: "Co-Founder & CEO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "AB",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0115",
        name: "Matthias Wickenburg",
        role: "Co-Founder & CTO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "MW",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Sales And Marketing",
    geography: "US",
    round: "Series B",
    ask: "$30M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Medium",
    submitted: "2026-06-23",
    thesisFit: null,
    realEvent: "$30M Series B announced 2026-06-23",
    interviewUrl: null,
    website: "https://www.attention.com/",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0107-attention/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0107-attention.md",
    companyStatus: "active",
    vehicle: "MGV.VC",
    portfolioYear: 2022,
  },
  {
    id: "OPP-MGV-US-0108",
    company: "District Cover",
    oneLiner:
      "Active portfolio company in Finance And Insurance. More than $7M raised in a 2024 funding round",
    founders: [
      {
        id: "FND-MGV-US-0116",
        name: "Patrick Girouard",
        role: "Founder and Chief Executive Officer",
        assessed: false,
        avatar: {
          type: "initials",
          value: "PG",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Finance And Insurance",
    geography: "US",
    round: "Venture",
    ask: "Public card",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Medium",
    submitted: "2024-07-23",
    thesisFit: null,
    realEvent: "More than $7M raised in a 2024 funding round",
    interviewUrl: null,
    website: "https://districtcover.com/",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0108-district-cover/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0108-district-cover.md",
    companyStatus: "active",
    vehicle: "MGV.VC",
    portfolioYear: 2022,
  },
  {
    id: "OPP-MGV-US-0109",
    company: "Buildstock",
    oneLiner:
      "Active portfolio company in Property And Real Estate. $1.6M pre-seed announced 2024-02-22; MGV participated",
    founders: [
      {
        id: "FND-MGV-US-0117",
        name: "Kathryn Thiele",
        role: "Founder & CEO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "KT",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0118",
        name: "Wilson Kriegel",
        role: "co-founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "WK",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Property And Real Estate",
    geography: "US",
    round: "Pre Seed",
    ask: "$1.6M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Medium",
    submitted: "2024-02-22",
    thesisFit: null,
    realEvent: "$1.6M pre-seed announced 2024-02-22; MGV participated",
    interviewUrl: null,
    website: "https://buildstock.com/",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0109-buildstock/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0109-buildstock.md",
    companyStatus: "active",
    vehicle: "MGV.VC",
    portfolioYear: 2022,
  },
  {
    id: "OPP-MGV-US-0110",
    company: "Salut",
    oneLiner: "Unclear portfolio company in Healthcare. $1.25M financing announced 2020-11-30",
    founders: [
      {
        id: "FND-MGV-US-0119",
        name: "Matthew DiPietro",
        role: "Founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "MD",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Healthcare",
    geography: "US",
    round: "Seed",
    ask: "$1.3M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Low",
    submitted: "2020-11-30",
    thesisFit: null,
    realEvent: "$1.25M financing announced 2020-11-30",
    interviewUrl: null,
    website: "https://joinsalut.com/",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0110-salut/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0110-salut.md",
    companyStatus: "unclear",
    vehicle: "MGV.VC",
    portfolioYear: 2020,
  },
  {
    id: "OPP-MGV-US-0111",
    company: "OfficeTogether",
    oneLiner:
      "Acquired portfolio company in Human Resources. $2.2M seed; acquired by Envoy on 2022-08-02",
    founders: [
      {
        id: "FND-MGV-US-0120",
        name: "Amy Yin",
        role: "CEO and Founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "AY",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Human Resources",
    geography: "US",
    round: "Seed",
    ask: "$2.2M",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Low",
    submitted: "2020-12-08",
    thesisFit: null,
    realEvent: "$2.2M seed; acquired by Envoy on 2022-08-02",
    interviewUrl: null,
    website: "https://envoy.com/workplace-management/together-is-better-with-officetogether",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0111-officetogether/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0111-officetogether.md",
    companyStatus: "acquired",
    vehicle: "MGV.VC",
    portfolioYear: 2020,
  },
  {
    id: "OPP-MGV-US-0112",
    company: "Downstream",
    oneLiner:
      "Acquired portfolio company in Sales And Marketing. Acquired by Jungle Scout in March 2021; terms undisclosed",
    founders: [
      {
        id: "FND-MGV-US-0121",
        name: "Connor Folley",
        role: "Co-Founder & CEO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "CF",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0122",
        name: "Salim Hamed",
        role: "Co-Founder & CTO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "SH",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Sales And Marketing",
    geography: "US",
    round: "Portfolio History",
    ask: "Public card",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Low",
    submitted: "2019",
    thesisFit: null,
    realEvent: "Acquired by Jungle Scout in March 2021; terms undisclosed",
    interviewUrl: null,
    website:
      "https://www.junglescout.com/press/press-releases/walmart-connect-now-available-on-downstream-by-jungle-scout/",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0112-downstream/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0112-downstream.md",
    companyStatus: "acquired",
    vehicle: "MGV.VC",
    portfolioYear: 2019,
  },
  {
    id: "OPP-MGV-US-0113",
    company: "HeyDoctor",
    oneLiner:
      "Acquired portfolio company in Healthcare. Acquired by GoodRx on 2019-04-18 for $14.3M cash; later rebranded GoodRx Care",
    founders: [
      {
        id: "FND-MGV-US-0123",
        name: "Brendan Levy",
        role: "Founder/CEO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "BL",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0124",
        name: "Kyle Alwyn",
        role: "Founder/Chief Technical Officer",
        assessed: false,
        avatar: {
          type: "initials",
          value: "KA",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0125",
        name: "Rohit Malhotra",
        role: "Founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "RM",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Healthcare",
    geography: "US",
    round: "Portfolio History",
    ask: "Public card",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Low",
    submitted: "2018",
    thesisFit: null,
    realEvent: "Acquired by GoodRx on 2019-04-18 for $14.3M cash; later rebranded GoodRx Care",
    interviewUrl: null,
    website: "https://www.goodrx.com/care",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0113-heydoctor/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0113-heydoctor.md",
    companyStatus: "acquired",
    vehicle: "MGV.VC",
    portfolioYear: 2018,
  },
  {
    id: "OPP-MGV-US-0114",
    company: "Buzzle.ai",
    oneLiner:
      "Inactive portfolio company in Sales And Marketing. Y Combinator currently marks the company Inactive",
    founders: [
      {
        id: "FND-MGV-US-0126",
        name: "Bhairav Mehta",
        role: "Founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "BM",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0127",
        name: "Adithya Ramanathan",
        role: "Founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "AR",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Sales And Marketing",
    geography: "US",
    round: "Portfolio History",
    ask: "Public card",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Low",
    submitted: "2021",
    thesisFit: null,
    realEvent: "Y Combinator currently marks the company Inactive",
    interviewUrl: null,
    website: "https://www.ycombinator.com/companies/buzzle",
    logoUrl: null,
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0114-buzzle-ai.md",
    companyStatus: "inactive",
    vehicle: "MGV.VC",
    portfolioYear: 2021,
  },
  {
    id: "OPP-MGV-US-0115",
    company: "Aviary Health (formerly Recora care services)",
    oneLiner:
      "Active Rebrand portfolio company in Healthcare. Recora launched the Aviary Health brand on 2026-04-07",
    founders: [
      {
        id: "FND-MGV-US-0128",
        name: "Abhi Chandra",
        role: "Co-Founder & CEO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "AC",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0129",
        name: "Ed Wu, MD",
        role: "Co-Founder & COO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "EW",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0130",
        name: "Vivek Vishwanath",
        role: "Co-Founder & CGO",
        assessed: false,
        avatar: {
          type: "initials",
          value: "VV",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Healthcare",
    geography: "US",
    round: "Portfolio History",
    ask: "Public card",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Medium",
    submitted: "2020",
    thesisFit: null,
    realEvent: "Recora launched the Aviary Health brand on 2026-04-07",
    interviewUrl: null,
    website: "https://www.aviaryhealth.com/",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0115-aviary-health/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0115-aviary-health.md",
    companyStatus: "active_rebrand",
    vehicle: "MGV.VC",
    portfolioYear: 2020,
  },
  {
    id: "OPP-MGV-US-0116",
    company: "Globe (formerly Recharge)",
    oneLiner:
      "Unclear portfolio company in Property And Real Estate. Predecessor Recharge reportedly raised about $10M; Globe faced regulatory pressure in 2020",
    founders: [
      {
        id: "FND-MGV-US-0131",
        name: "Manny (Emmanuel) Bamfo",
        role: "co-founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "MB",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0132",
        name: "Erix Xu",
        role: "co-founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "EX",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0133",
        name: "Will Johnson",
        role: "Recharge co-founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "WJ",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
      {
        id: "FND-MGV-US-0134",
        name: "Christopher Lo",
        role: "Recharge co-founder",
        assessed: false,
        avatar: {
          type: "initials",
          value: "CL",
          basis: "neutral placeholder; no founder photo stored",
        },
      },
    ],
    stage: "Portfolio",
    sector: "Property And Real Estate",
    geography: "US",
    round: "Portfolio History",
    ask: "Public card",
    assessed: false,
    founderScore: null,
    marketScore: null,
    ideaMarketScore: null,
    trustScore: null,
    urgency: "Low",
    submitted: "2019",
    thesisFit: null,
    realEvent:
      "Predecessor Recharge reportedly raised about $10M; Globe faced regulatory pressure in 2020",
    interviewUrl: null,
    website: "https://globeliving.com/",
    logoUrl: "/opportunity-db/assets/OPP-MGV-US-0116-globe/logo.png",
    sourceCardUrl: "/opportunity-db/cards/OPP-MGV-US-0116-globe.md",
    companyStatus: "unclear",
    vehicle: "MGV.VC",
    portfolioYear: 2019,
  },
] satisfies Startup[];
