/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as BoardRouteImport } from './routes/board'
import { Route as DiligenceRouteImport } from './routes/diligence'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as FounderPortalRouteImport } from './routes/founder-portal'
import { Route as FounderWorldRouteImport } from './routes/founder-world'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemoRouteImport } from './routes/memo'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DiligenceRoute = DiligenceRouteImport.update({
  id: '/diligence',
  path: '/diligence',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderPortalRoute = FounderPortalRouteImport.update({
  id: '/founder-portal',
  path: '/founder-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderWorldRoute = FounderWorldRouteImport.update({
  id: '/founder-world',
  path: '/founder-world',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoRoute = MemoRouteImport.update({
  id: '/memo',
  path: '/memo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/apply': typeof ApplyRoute
  '/board': typeof BoardRoute
  '/diligence': typeof DiligenceRoute
  '/founder': typeof FounderRoute
  '/founder-portal': typeof FounderPortalRoute
  '/founder-world': typeof FounderWorldRoute
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/memo': typeof MemoRoute
  '/references': typeof ReferencesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/apply': typeof ApplyRoute
  '/board': typeof BoardRoute
  '/diligence': typeof DiligenceRoute
  '/founder': typeof FounderRoute
  '/founder-portal': typeof FounderPortalRoute
  '/founder-world': typeof FounderWorldRoute
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/memo': typeof MemoRoute
  '/references': typeof ReferencesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/apply': typeof ApplyRoute
  '/board': typeof BoardRoute
  '/diligence': typeof DiligenceRoute
  '/founder': typeof FounderRoute
  '/founder-portal': typeof FounderPortalRoute
  '/founder-world': typeof FounderWorldRoute
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/memo': typeof MemoRoute
  '/references': typeof ReferencesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/apply'
    | '/board'
    | '/diligence'
    | '/founder'
    | '/founder-portal'
    | '/founder-world'
    | '/interviews'
    | '/login'
    | '/memo'
    | '/references'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/apply'
    | '/board'
    | '/diligence'
    | '/founder'
    | '/founder-portal'
    | '/founder-world'
    | '/interviews'
    | '/login'
    | '/memo'
    | '/references'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/apply'
    | '/board'
    | '/diligence'
    | '/founder'
    | '/founder-portal'
    | '/founder-world'
    | '/interviews'
    | '/login'
    | '/memo'
    | '/references'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  ApplyRoute: typeof ApplyRoute
  BoardRoute: typeof BoardRoute
  DiligenceRoute: typeof DiligenceRoute
  FounderRoute: typeof FounderRoute
  FounderPortalRoute: typeof FounderPortalRoute
  FounderWorldRoute: typeof FounderWorldRoute
  InterviewsRoute: typeof InterviewsRoute
  LoginRoute: typeof LoginRoute
  MemoRoute: typeof MemoRoute
  ReferencesRoute: typeof ReferencesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diligence': {
      id: '/diligence'
      path: '/diligence'
      fullPath: '/diligence'
      preLoaderRoute: typeof DiligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder-portal': {
      id: '/founder-portal'
      path: '/founder-portal'
      fullPath: '/founder-portal'
      preLoaderRoute: typeof FounderPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder-world': {
      id: '/founder-world'
      path: '/founder-world'
      fullPath: '/founder-world'
      preLoaderRoute: typeof FounderWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memo': {
      id: '/memo'
      path: '/memo'
      fullPath: '/memo'
      preLoaderRoute: typeof MemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  ApplyRoute: ApplyRoute,
  BoardRoute: BoardRoute,
  DiligenceRoute: DiligenceRoute,
  FounderRoute: FounderRoute,
  FounderPortalRoute: FounderPortalRoute,
  FounderWorldRoute: FounderWorldRoute,
  InterviewsRoute: InterviewsRoute,
  LoginRoute: LoginRoute,
  MemoRoute: MemoRoute,
  ReferencesRoute: ReferencesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
