// Loads thesis.json (the single source of fund criteria) and flattens the
// fields the Developing stage consumes. Full structure stays available on
// `raw` for founder scoring and the interview agent.
//
// Per sun/tech-video-staging/tech-spec.md §9.1: "Store the fund thesis as
// human-readable Markdown, structured JSON policy, and a version
// identifier." JSON stays the single editable source of truth (edited in
// Settings, read by the pipeline) — renderThesisMarkdown derives the
// Markdown from it on every write, so the two can never drift.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export function loadThesis() {
  const here = dirname(fileURLToPath(import.meta.url));
  const raw = JSON.parse(readFileSync(join(here, "..", "thesis.json"), "utf8"));
  return {
    raw,
    sectors: raw.fund.sectors,
    maxCheckUsd: raw.fund.checkSizeUsd.max,
    targetOwnership: raw.fund.targetOwnership,
    maxOpenGaps: raw.fund.maxOpenGaps,
    compsMultiple: raw.negotiation.compsMultiple,
    founderAskMultiple: raw.negotiation.founderAskMultiple,
    batnaRef: raw.negotiation.batnaRef,
    levers: raw.negotiation.levers,
  };
}

const money = (n) => (n >= 1e6 ? `$${n / 1e6}M` : `$${Math.round(n / 1e3)}K`);
const pct = (n) => `${Math.round(n * 100)}%`;

/** Human-readable rendering of thesis.json — regenerated on every write, not
 * hand-maintained, so it can never drift from the JSON that's actually read. */
export function renderThesisMarkdown(raw) {
  const f = raw.fund;
  const n = raw.negotiation;
  const fc = raw.founderCriteria;
  const er = raw.evidenceRules;
  const subScoreRows = Object.entries(fc.subScores)
    .map(([k, v]) => `| ${k} | ${pct(v.weight)} | ${v.floor} |`)
    .join("\n");
  const bandRows = Object.entries(er.trustBands)
    .map(([k, [lo, hi]]) => `| ${k} | ${lo}–${hi} |`)
    .join("\n");

  return `# Fund thesis — ${raw.id} (v${raw.version ?? 1})

Generated from \`thesis.json\` — do not edit this file directly, it is
overwritten on every thesis save. Edit the thesis in Settings, or edit
\`thesis.json\` and this file regenerates on the next \`POST /thesis\`.

**Last updated:** ${raw.updatedAt ?? "unknown"}

## Fund

- **Sectors:** ${f.sectors.join(", ")}
- **Stages:** ${f.stages.join(", ")}
- **Geographies:** ${f.geographies.join(", ")}
- **Check size:** ${money(f.checkSizeUsd.min)}–${money(f.checkSizeUsd.max)}
- **Target ownership:** ${pct(f.targetOwnership)}
- **Risk appetite:** ${f.riskAppetite}
- **Max open evidence gaps:** ${f.maxOpenGaps}

## Negotiation

- **Comps multiple:** ${n.compsMultiple}× · **Founder-ask multiple:** ${n.founderAskMultiple}×
- **BATNA reference:** ${n.batnaRef}
- **Levers:** ${n.levers.join(", ")}
- **No-bluff policy:** ${n.noBluff ? "yes" : "no"} · **Reservation price requires human approval:** ${n.reservationRequiresHumanApproval ? "yes" : "no"}

## Founder criteria

Five sub-scores, weights sum to 1. A floor is a ceiling trait — below it,
the founder axis is capped regardless of other scores.

| Sub-score | Weight | Floor |
|---|---:|---:|
${subScoreRows}

- **Never scored:** ${fc.doNotScore.join(", ")}
- **Behavioral signals:** ${fc.behavioralSignals.join(", ")}

## Evidence and trust bands

${er.scale}.

| Band | Range |
|---|---:|
${bandRows}

Self-reported claims default to ${er.selfReportedDefault}/100; contradicted
claims default to ${er.contradictedDefault}/100. Verified status requires an
independent source: ${er.verifiedRequiresIndependentSource ? "yes" : "no"}.

---
*This file is generated — see \`laura/pipeline/lib/thesis.js\` (renderThesisMarkdown) and \`laura/pipeline/thesis.json\` for the source of truth.*
`;
}
